### ISSUE TITLE
IS there a way to *export* Notion pages as MD?

### ISSUE THREAD

**Issue by BenBlumer** [Cobertos/md2notion#12]
Thanks for the package! I'm hoping someone here will have insight: What's the best way to programmatically export notion pages as markdown?

**Comment by Cobertos** [comment]
Notion has a Markdown export feature, though I've never used it so I can't say what sort of quality it has.

Have you tried using that already?

![image](https://user-images.githubusercontent.com/6759176/81525244-104eeb00-9322-11ea-852b-f6126dc20584.png)
![image](https://user-images.githubusercontent.com/6759176/81525263-1b098000-9322-11ea-9615-f91f0c93adb5.png)

**Comment by BenBlumer** [comment]
Yeah - it works. I'm looking for a way to access that programmitically.

 If you're curious: I'm writing a piece of code to monitor changes in notion docs and trigger an export to MD, Which I then convert to ODT and upload to google docs. And vice versa. The idea is to keep Google docs synched with Notion and vice versa. 

> Notion has a Markdown export feature, though I've never used it so I can't say what sort of quality it has.
> 
> Have you tried using that already?
> 
> ![image](https://user-images.githubusercontent.com/6759176/81525244-104eeb00-9322-11ea-852b-f6126dc20584.png)
> ![image](https://user-images.githubusercontent.com/6759176/81525263-1b098000-9322-11ea-9615-f91f0c93adb5.png)

**Comment by Cobertos** [comment]
Oh I see... I feel like I recall there being an API endpoint for this. I don't see any in `notion-py` but after looking at the API calls from the web client it looks like there's a way to at least call it programmatically.

There's an `enqueueTask` endpoint that begins the export with the payload shown
![image](https://user-images.githubusercontent.com/6759176/81525851-029a6500-9324-11ea-9f3a-d95234ea0696.png)
![image](https://user-images.githubusercontent.com/6759176/81525841-f9a99380-9323-11ea-9b00-723b7c486e1f.png)

and then there's a `getTasks` endpoint that allows you to get the final output. The result is in the payload
![image](https://user-images.githubusercontent.com/6759176/81525882-1940bc00-9324-11ea-8a22-30c2ceec967e.png)
![image](https://user-images.githubusercontent.com/6759176/81525909-29f13200-9324-11ea-9ebd-78d036d490a1.png)

If you want to see this and tinker with it yourself, you can open the Notion web client in Chrome, open the network tab, and then do an export.

**Comment by AlexMikhalev** [comment]
For those who find this ticket googling "notion to markdown" export:
Gist to export blog post using notion-py https://gist.github.com/AlexMikhalev/8c8ff3b7d657a106b39a1038715aa56b
