### ISSUE TITLE
`>`  and other kinds of "Blocks"?

### ISSUE THREAD

**Issue by haakonstorm** [Cobertos/md2notion#14]
Hi Cobertos and thanks for `md2notion`! 
As I don't know Python well enough to use `notion-py`, I piggybacked on your skills and wrote a quick `zsh` wrapper around this script, so I can use `Notion` as a place to dump various system logs. Basically I take whatever comes on `stdin`, dumps that to file and hands it to `md2notion` who does a great job. 
However, I'd love for somehow to be able to add "toggle" Blocks in Notion. 
You know the ones that start with `>` in Notion, but *isn't* a QuoteBlock?
Possible somehow?

**Comment by Cobertos** [comment]
Woops, forgot about this one.

Are you looking to support some sort of custom Markdown > Toggle Block conversion or would you like to handle it in the script?

I can give some code snippets the next time I loop back to this

**Comment by haakonstorm** [comment]
Anything goes! 
What would be awesome would be somehow to use `md2notion` as a CLI interface to Notion. My daemonized script is trying to parse what the user is doing, and decide when the activity changed context. Continously logging to inside a temporarily named, open, "toggle", and then upon changing context, somehow retroactively changing the text in the toggle block itself, then closing the toggle block and opening a new. As in opening and closing chapters in a book, that's the idea.
