### ISSUE TITLE
Relative images not found

### ISSUE THREAD

**Issue by mattstratford** [Cobertos/md2notion#15]
Thanks for writing this script. I can successfully import text Markdown files with it. However, in testing this it's failing to locate relative images.

I have a directory structure on Mac `~/Desktop/test/` where the contents of `test` are a file `Favorite tweet – PizzoniGiada – June 17, 2020 at 0901AM.md` and a folder `Favorite tweet – PizzoniGiada – June 17, 2020 at 0901AM` which contains a single image `image_1.jpeg`.

Running using `Python 3.8.3` and the latest version of `md2notion` installed via `pip3 install md2notion`, I am getting the following:

```
ELSLABM-155961:Desktop stratfordm$ python3 -m md2notion {token_2} https://www.notion.so/Test-0192acd694d443ec924a2a5de270c90d /Users/stratfordm/Desktop/test/Favorite\ tweet\ – PizzoniGiada\ –\ June\ 17\,\ 2020\ at\ 0901AM.md 
Initializing Notion.so client...
Getting target PageBlock...
Uploading /Users/stratfordm/Desktop/test/Favorite tweet – PizzoniGiada – June 17, 2020 at 0901AM.md to Notion.so at page Favorite tweet – PizzoniGiada – June 17, 2020 at 0901AM.md...
Uploading ImageBlock, 4/7 (57.1%)ERROR: Local image '/Users/stratfordm/Desktop/test/Favorite%20tweet%20%E2%80%93%C2%A0PizzoniGiada%20%E2%80%93%20June%2017,%202020%20at%200901AM/image_1.jpeg' not found to upload. Skipping...
Uploading TextBlock, 7/7 (100.0%)EL
```

The end result is a note created but without the image attachment. 

Hope this helps.

**Comment by Cobertos** [comment]
Couple things:

* I see Windows-esque paths (`/Users/stratfordm/Desktop/test/`) so perhaps I used an incorrect pathing module.
* URLEncoded image links, perhaps a similar problem to #13

Will give a look next time I'm on computer

**Comment by Cobertos** [comment]
Hmm, so after looking at this further, it looks like links and images with spaces are actually _supposed_ to be interpreted as text by CommonMark

![image](https://user-images.githubusercontent.com/6759176/91138008-c691d280-e67c-11ea-8941-0ae269c0b572.png)

So my suggestion is it's probably better to rename your attachments, but for the sake of utility, it might be nice if `md2notion` checked the URLs for `file://` syntax as well as URL decode and potentially try all three strings as paths to find a file.

**Comment by Cobertos** [comment]
Alright, this should now work for you in v2.1.1. We can reopen if it doesn't

**Comment by mattstratford** [comment]
Thanks! I'll take a look presently…
