### ISSUE TITLE
Support for checkbox.

### ISSUE THREAD

**Issue by mshiyaf** [Cobertos/md2notion#18]
I cannot find conversion for a checkbox block. It renders as a normal bulleted list.

**Comment by Cobertos** [comment]
`md2notion` uses [`mistletoe`](https://github.com/miyuchina/mistletoe) for Markdown processing which is based on CommonMark [which doesn't support GitHub Markdown Flavor (GFM) checkboxes](https://talk.commonmark.org/t/support-for-gfm-like-checkboxes/2007).

I originally looked at adding it as a new token...

<details><summary>As a new token...</summary>
<p>

`mistletoe` makes it [super easy to add new tokens](https://github.com/miyuchina/mistletoe#a-new-token). We should be able to add a new block token to the renderer that handles this. Something like the following:

```
from md2notion.NotionPyRenderer import NotionPyRenderer
from notion.block import TodoBlock

class GFMCheckbox(BlockToken):
    """
    Similar to ListItemBlock but has an extra /\[(x )\]/i 
    Attributes:
        children (list): a list of
    TODO, use the pattern = from ListItemBlock but with the extra regex above
    """
    pass

class NotionPyWithTodoBlockRenderer(NotionPyRenderer):
    def __init__(self):
        super().__init__(GFMCheckbox)
```

</p>
</details>

... but then realized this can just be handled in the `ListItem` handling directly

```python
import re
from md2notion.NotionPyRenderer import NotionPyRenderer
from notion.block import TodoBlock

class NotionPyWithTodoBlockRenderer(NotionPyRenderer):
    def render_list_item(self, token):
        # Lists can have "children" (nested lists, nested images...), so we need
        # to render out all the nodes and sort through them to find the string
        # for this item and any children
        rendered = self.renderMultiple(token.children)
        children = [b for b in rendered if b['type'] != TextBlock]
        strings = [s['title'] for s in rendered if s['type'] == TextBlock]

		# Figure out which type of block we need to render
        leaderContainsNumber = re.match(r'\d', token.leader) #Contains a number
        renderType = None
		if leaderContainsNumber:
            renderType = NumberedListBlock
        else if re.match(r"^\[[x ]\]", strings, re.I):
            renderType = TodoBlock
        else:
            renderType = BulletedListBlock

        return {
            'type': renderType,
            'title': "".join(strings),
            'children': children
        }
```

If you use this renderer with the [`notionPyRendererCls` kwarg](https://github.com/Cobertos/md2notion/blob/master/md2notion/upload.py#L83) it should handle it.

**Comment by Cobertos** [comment]
![image](https://user-images.githubusercontent.com/6759176/91145440-723e2100-e683-11ea-886d-c947dcd0541a.png)
 Ended up adding it, should be in the next version

**Comment by shiyaf-texol** [comment]
That's great to hear, since personally I use a lot of TODO items not finding checkbox conversion made me feel incomplete.
Hoping to see the new version released soon.

**Comment by Cobertos** [comment]
Added in v2.1.1
