### ISSUE TITLE
Can I have a sync between a notion page and a corresponding md pages?

### ISSUE THREAD

**Issue by dummifiedme** [Cobertos/md2notion#25]
I was thinking of notion with Obsidian, like to publish the whole vault if possible.

**Comment by Cobertos** [comment]
Publishing Obsidian to notion?

**Comment by dummifiedme** [comment]
Basically, I was asking if there can be a sync between notion and a folder (containing md files)

**Comment by Cobertos** [comment]
Not out of the box, but you could set up a file watcher and then run

`python -m md2notion [token_v2] [page-url] [...markdown_path_glob_or_url]`

with a glob to your folder whenever a file changes. Depending on how many .md files are in there, upload will be probably be somewhat slow unfortunately.

**Comment by dummifiedme** [comment]
Okay. WIll try to have that. 
But at the same time, I can't have the edited pages back in my folder right?

**Comment by Cobertos** [comment]
Ah, no, `md2notion` only does import, not export.

**Comment by dummifiedme** [comment]
Yeah. I think there is another script that does the opposite. But it would be risky by a bit :p

**Comment by dummifiedme** [comment]
Anyway, thanks :)
