### ISSUE TITLE
Upload creates new blocks on subsequent runs

### ISSUE THREAD

**Issue by coryodaniel** [Cobertos/md2notion#3]
Running the upload command against a PageBlock results in duplicate files on subsequent runs.

`python -m md2notion.upload [token_v2] [page-url] ./docs/*.md`

Results in:
* doc-1.md
* doc-2.md

Running it again, will append additional files instead of updating the existing ones.

`python -m md2notion.upload [token_v2] [page-url] ./docs/*.md`

Results in:
* doc-1.md
* doc-2.md
* doc-1.md
* doc-2.md

**Comment by coryodaniel** [comment]
Thanks by the way. This is a pretty awesome tool!

**Comment by Cobertos** [comment]
That was a pain point for me as well. Unfortunately I see no easy way to implement this feature. There's a lot of things the user can do with the documents between generations that would make the algorithm to match up previous pages to newly generated ones either very flaky or very challenging to write, test, and maintain.

I'm open to ideas and PRs though.

**Comment by coryodaniel** [comment]
Yeah I'm not positive either. I ended up writing a markdown file to notion page title function and I use that to look up the page and replace it if its there or create a new one. 🤷‍♂

**Comment by Cobertos** [comment]
Yeah, I think I'd rather leave this as a tool to just convert and upload into Notion. If the end user wants to remove old notes or something else, they can write that in their own script.

Closing as won't fix, but if someone has a compelling reason im open to more discussion

**Comment by Cobertos** [comment]
Ended up maybe fixing your issue? If you wanted to take a look at https://github.com/Cobertos/md2notion/pull/11
