### ISSUE TITLE
401 Client Error: Unauthorized for url: https://www.notion.so/api/v3/loadUserContent

### ISSUE THREAD

**Issue by Wikhar** [Cobertos/md2notion#32]
Hello,
This morning I tried your module with my notion. But i have always this error. I tried to refresh the Token_v2 a couple of times, but nothing change... Have you an idea ? 

Best Regards.

**Comment by Wikhar** [comment]
Ok I don't understand .. uninstall  notion and md2notion package,install again, retry and it works..
Sry for this issue.

**Comment by cavaunpeu** [comment]
Getting this error now myself.
