### ISSUE TITLE
LaTeX equation parsing error

### ISSUE THREAD

**Issue by Theigrams** [Cobertos/md2notion#33]
I use this code to upload my file:
```python
with open("a.md", "r", encoding="utf-8") as mdFile:
    newPage = page.children.add_new(PageBlock, title="TestMarkdown Upload")
    upload(mdFile, newPage, notionPyRendererCls=addLatexExtension(NotionPyRenderer))
```

And my file  `a.md` is that:
```markdown
$\phi\left(v_{i, l}\right)=\mathbf{R}_{i} v_{i, l}+t_{i}$


$$
P\left(v_{i, l}\right)=\sum_{j \neq i}^{M} \frac{1}{M^{\prime}} \mathcal{N}\left(\mathbf{R}_{i} v_{i, l}+t_{i} ; \mathbf{R}_{j} v_{j, c(j, l)}+t_{j}, \Sigma\right)
$$

```

It shows in typora:
![image](https://user-images.githubusercontent.com/26341831/112740404-53a05f80-8faf-11eb-9507-b26bf3bc1fcd.png)

But in Notion, the subscript `_`  seems to be parsed as `*` or null
![image](https://user-images.githubusercontent.com/26341831/112740426-86e2ee80-8faf-11eb-9823-21b9749fca69.png)

**Comment by Cobertos** [comment]
Same as #31, I will look at tonight

**Comment by Cobertos** [comment]
Closing as duplicate, working on in #31
