### ISSUE TITLE
Import as database entry, not page?

### ISSUE THREAD

**Issue by soneji** [Cobertos/md2notion#37]
Hi

I am new to notion and am trying to use your incredible tool to import my markdown files to notion, I love how well it works with images, of which i have many in my notes!

I was wondering whether it's possible to import each md file as an entry, not a page. Maybe i'm just misunderstanding how to use the tool, as I am new to notion. 

Thanks so much

**Comment by Cobertos** [comment]
So you want to import multiple files as blocks into a single page?

The `--append` flag will do that. Instead of creating a child Notion page for each `.md` file, all the files will be uploaded into the specific Notion page, one after the other

**Comment by soneji** [comment]
I was looking at it again, and I think the default settings are what I want. I have created a list view within my page, and imported the markdown files to that page, but my markdown files aren't showing up in the list. Could there be any reason for this? 

They show up correctly however when I use <kbd>Cmd</kbd>+<kbd>k</kbd> and search for the `.md` file.

**Comment by soneji** [comment]
I've been reading a little more about the terminology and I think my question is:

##### How do I import `.md` files into a database?

**Comment by soneji** [comment]
Actually I figured it out, I think the items were inside the page, but hidden, as the page was a full screen database.
I got around this by moving the database into another page and then moving the pages into the database. Steep learning curve 🤷 
Thank you so much for your help though, and your amazing plugin :)
